// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
ui_Screen6 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Roller5 = lv_roller_create(ui_Screen6);
lv_roller_set_options( ui_Roller5, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller5, 100);
lv_obj_set_width( ui_Roller5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller5, -75 );
lv_obj_set_y( ui_Roller5, -20 );
lv_obj_set_align( ui_Roller5, LV_ALIGN_CENTER );

ui_Roller6 = lv_roller_create(ui_Screen6);
lv_roller_set_options( ui_Roller6, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller6, 100);
lv_obj_set_width( ui_Roller6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller6, -25 );
lv_obj_set_y( ui_Roller6, -20 );
lv_obj_set_align( ui_Roller6, LV_ALIGN_CENTER );

ui_Roller7 = lv_roller_create(ui_Screen6);
lv_roller_set_options( ui_Roller7, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller7, 100);
lv_obj_set_width( ui_Roller7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller7, 25 );
lv_obj_set_y( ui_Roller7, -20 );
lv_obj_set_align( ui_Roller7, LV_ALIGN_CENTER );

ui_Roller8 = lv_roller_create(ui_Screen6);
lv_roller_set_options( ui_Roller8, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller8, 100);
lv_obj_set_width( ui_Roller8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller8, 75 );
lv_obj_set_y( ui_Roller8, -20 );
lv_obj_set_align( ui_Roller8, LV_ALIGN_CENTER );

ui_SetTimeButton = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_SetTimeButton, 100);
lv_obj_set_height( ui_SetTimeButton, 30);
lv_obj_set_x( ui_SetTimeButton, 0 );
lv_obj_set_y( ui_SetTimeButton, 60 );
lv_obj_set_align( ui_SetTimeButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SetTimeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SetTimeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_SetTimeButton);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Set Time");

lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}
