// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TimerArc = lv_arc_create(ui_Screen4);
lv_obj_set_width( ui_TimerArc, 240);
lv_obj_set_height( ui_TimerArc, 240);
lv_obj_set_align( ui_TimerArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TimerArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

lv_obj_set_style_arc_color(ui_TimerArc, lv_color_hex(0x777777), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TimerArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_opa(ui_TimerArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_EndTimerButton = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_EndTimerButton, 100);
lv_obj_set_height( ui_EndTimerButton, 30);
lv_obj_set_x( ui_EndTimerButton, 0 );
lv_obj_set_y( ui_EndTimerButton, 60 );
lv_obj_set_align( ui_EndTimerButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_EndTimerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_EndTimerButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_EndTimerButton);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"End");

}
