// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_ImageWatchface;
extern lv_obj_t *ui_DigitalTimeLabel;
extern lv_obj_t *ui_ImageArmHour;
extern lv_obj_t *ui_ImageArmMinute;
extern lv_obj_t *ui_ImageArmSecond;
extern lv_obj_t *ui_BatteryVoltageLabel;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_BrightnessArc;
extern lv_obj_t *ui_Label3;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3( lv_event_t * e);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Roller1;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Roller3;
extern lv_obj_t *ui_Roller4;
extern lv_obj_t *ui_StartTimerButton;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label7;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_TimerArc;
extern lv_obj_t *ui_EndTimerButton;
extern lv_obj_t *ui_Label2;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5( lv_event_t * e);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_DataArc1;
extern lv_obj_t *ui_DataArc2;
extern lv_obj_t *ui_DataArc3;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6( lv_event_t * e);
extern lv_obj_t *ui_Screen6;
extern lv_obj_t *ui_Roller5;
extern lv_obj_t *ui_Roller6;
extern lv_obj_t *ui_Roller7;
extern lv_obj_t *ui_Roller8;
extern lv_obj_t *ui_SetTimeButton;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_watchface240_png);   // assets\watchface240.png
LV_IMG_DECLARE( ui_img_armhour_png);   // assets\armHour.png
LV_IMG_DECLARE( ui_img_armminute_png);   // assets\armMinute.png
LV_IMG_DECLARE( ui_img_armsecond_png);   // assets\armSecond.png
LV_IMG_DECLARE( ui_img_out1_png);   // assets\out1.png
LV_IMG_DECLARE( ui_img_out2_png);   // assets\out2.png
LV_IMG_DECLARE( ui_img_out3_png);   // assets\out3.png
LV_IMG_DECLARE( ui_img_out4_png);   // assets\out4.png
LV_IMG_DECLARE( ui_img_out5_png);   // assets\out5.png
LV_IMG_DECLARE( ui_img_out6_png);   // assets\out6.png
LV_IMG_DECLARE( ui_img_out7_png);   // assets\out7.png
LV_IMG_DECLARE( ui_img_out8_png);   // assets\out8.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
